"""Self-hosted PostgreSQL data access layer for SafeBridge AI.
Talks directly to a Postgres instance via psycopg2 — no Supabase cloud
service is involved. Set DATABASE_URL in .streamlit/secrets.toml, e.g.:
    DATABASE_URL = "postgresql://appuser:yourpassword@localhost:5432/safebridge"
"""
import base64
import os
import re
import secrets
import string
from contextlib import contextmanager
from datetime import datetime, timezone, timedelta

import psycopg2
import psycopg2.extras
import streamlit as st

_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'student',
    active INTEGER NOT NULL DEFAULT 1,
    force_password_change INTEGER NOT NULL DEFAULT 0,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE students ADD COLUMN IF NOT EXISTS force_password_change INTEGER NOT NULL DEFAULT 0;
ALTER TABLE students ADD COLUMN IF NOT EXISTS failed_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE students ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE SET NULL,
    anonymous INTEGER NOT NULL DEFAULT 0,
    original_report TEXT NOT NULL,
    incident_summary TEXT,
    category TEXT,
    location TEXT,
    severity TEXT,
    priority TEXT,
    status TEXT NOT NULL DEFAULT 'Pending Review',
    evidence_name TEXT,
    evidence TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    preferred_date TEXT NOT NULL,
    preferred_time TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'Requested',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    mood INTEGER NOT NULL,
    mood_label TEXT NOT NULL,
    note TEXT,
    week_start TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_student_week UNIQUE (student_id, week_start)
);

CREATE TABLE IF NOT EXISTS counselor_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    counselor_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    note TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reports_student ON reports(student_id);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_created ON reports(created_at);
CREATE INDEX IF NOT EXISTS idx_appointments_student ON appointments(student_id);
CREATE INDEX IF NOT EXISTS idx_checkins_student ON checkins(student_id);
CREATE INDEX IF NOT EXISTS idx_counselor_notes_report ON counselor_notes(report_id);

ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE counselor_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
"""

_RLS_POLICY_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'students' AND policyname = 'app_full_access') THEN
        CREATE POLICY app_full_access ON students FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'reports' AND policyname = 'app_full_access') THEN
        CREATE POLICY app_full_access ON reports FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'appointments' AND policyname = 'app_full_access') THEN
        CREATE POLICY app_full_access ON appointments FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'checkins' AND policyname = 'app_full_access') THEN
        CREATE POLICY app_full_access ON checkins FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'counselor_notes' AND policyname = 'app_full_access') THEN
        CREATE POLICY app_full_access ON counselor_notes FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'settings' AND policyname = 'app_full_access') THEN
        CREATE POLICY app_full_access ON settings FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;
"""

def _get_database_url():
    try:
        url = st.secrets.get("DATABASE_URL")
    except Exception:
        url = None
    return (url or os.environ.get("DATABASE_URL", "")).strip()

@contextmanager
def connection():
    dsn = _get_database_url()
    if not dsn:
        raise ConnectionError(
            "DATABASE_URL is not configured. Add it to .streamlit/secrets.toml, "
            'e.g. DATABASE_URL = "postgresql://appuser:yourpassword@localhost:5432/safebridge"'
        )
    conn = psycopg2.connect(dsn, cursor_factory=psycopg2.extras.RealDictCursor)
    try:
        yield conn
        conn.commit()
    finally:
        conn.close()

def is_supabase_connected() -> tuple[bool, str]:
    """Name kept for compatibility with app.py's import — checks the
    self-hosted Postgres connection, not Supabase's cloud service."""
    try:
        with connection() as conn:
            conn.cursor().execute("SELECT 1")
        return True, "Connected to PostgreSQL"
    except Exception as e:
        return False, str(e)

def init_db():
    """Create the schema if missing, seed default settings, and bootstrap a
    single secure admin account if the students table is completely empty.
    No demo accounts are ever created."""
    dsn = _get_database_url()
    if not dsn:
        return
    try:
        with connection() as conn:
            cur = conn.cursor()
            cur.execute(_SCHEMA_SQL)
            cur.execute(_RLS_POLICY_SQL)

            for key, value in (
                ("allow_anonymous_reports", "1"),
                ("external_ai_allowed", "0"),
                ("report_retention_days", "30"),
            ):
                cur.execute(
                    "INSERT INTO settings(key, value) VALUES(%s, %s) ON CONFLICT (key) DO NOTHING",
                    (key, value),
                )

            cur.execute("SELECT 1 FROM students LIMIT 1")
            if not cur.fetchone():
                from auth import hash_password
                temp_password = "".join(secrets.choice(string.ascii_letters + string.digits) for _ in range(16))
                cur.execute(
                    "INSERT INTO students(username, password_hash, display_name, role, active, "
                    "force_password_change, failed_attempts) VALUES(%s,%s,%s,%s,1,1,0)",
                    ("admin", hash_password(temp_password), "School Administrator", "admin"),
                )
                # Server-side only — check your terminal/hosting logs, never shown in the browser.
                print(f"[SafeBridge first-run] Bootstrap admin created — username: admin  temporary password: {temp_password}")
    except Exception as e:
        print(f"[SafeBridge] init_db failed: {e}")

# ── SQLite-syntax compatibility shim (in case any leftover SQL uses it) ─────
_COMPAT_REPLACEMENTS = [
    (re.compile(r"date\('now','start of month'\)", re.IGNORECASE), "date_trunc('month', now())"),
    (re.compile(r"datetime\('now'\)", re.IGNORECASE), "now()"),
]

def _to_pg(sql):
    sql = sql.replace("?", "%s")
    for pattern, replacement in _COMPAT_REPLACEMENTS:
        sql = pattern.sub(replacement, sql)
    return sql

def _decode_row_evidence(row):
    if row and isinstance(row, dict) and isinstance(row.get("evidence"), str):
        try:
            row["evidence"] = base64.b64decode(row["evidence"].encode("utf-8"))
        except Exception:
            pass
    return row

def query(sql, params=()):
    with connection() as conn:
        cur = conn.cursor()
        cur.execute(_to_pg(sql), params)
        try:
            rows = [dict(r) for r in cur.fetchall()]
        except psycopg2.ProgrammingError:
            return []
        return [_decode_row_evidence(r) for r in rows]

def one(sql, params=()):
    rows = query(sql, params)
    return rows[0] if rows else None

def execute(sql, params=()):
    pg_sql = _to_pg(sql)
    stripped = pg_sql.strip().upper()
    if stripped.startswith("INSERT") and "RETURNING" not in stripped:
        pg_sql = pg_sql.rstrip().rstrip(";") + " RETURNING id"
    with connection() as conn:
        cur = conn.cursor()
        cur.execute(pg_sql, params)
        try:
            row = cur.fetchone()
            if row and "id" in row:
                return row["id"]
        except psycopg2.ProgrammingError:
            pass
        return True

# ── Settings helpers ─────────────────────────────────────────────────────────
def get_setting(key, default=None):
    row = one("SELECT value FROM settings WHERE key=?", (key,))
    return row["value"] if row else default

def set_setting(key, value):
    execute(
        "INSERT INTO settings(key, value) VALUES(?,?) ON CONFLICT (key) DO UPDATE SET value=EXCLUDED.value",
        (key, str(value)),
    )

# ── Report creation ──────────────────────────────────────────────────────────
def create_report(student_id, anonymous, text, analysis, evidence=None):
    if len(text.strip()) < 10 or len(text) > 6000:
        raise ValueError("Reports must be between 10 and 6,000 characters.")

    evidence_name = None
    evidence_b64 = None
    if evidence:
        evidence_size = getattr(evidence, "size", None)
        if evidence_size is None:
            evidence_size = len(evidence.getvalue())
        if evidence_size > 5 * 1024 * 1024:
            raise ValueError("Evidence files must be 5 MB or smaller.")
        evidence_name = evidence.name
        evidence_b64 = base64.b64encode(evidence.getvalue()).decode("utf-8")

    return execute(
        "INSERT INTO reports(student_id,anonymous,original_report,incident_summary,category,location,"
        "severity,priority,evidence_name,evidence,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,now())",
        (None if anonymous else student_id, 1 if anonymous else 0, text, analysis.get("summary"),
         analysis.get("category"), analysis.get("location"), analysis.get("severity"),
         analysis.get("priority"), evidence_name, evidence_b64),
    )

# ── Retention ────────────────────────────────────────────────────────────────
def purge_old_resolved_reports(days=None):
    """Deletes resolved reports older than the retention window. Wire this into
    an OS-level cron job on the VM for hands-off retention, or trigger it
    manually from the admin Settings page."""
    days = int(days or get_setting("report_retention_days", 30))
    cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
    with connection() as conn:
        cur = conn.cursor()
        cur.execute("DELETE FROM reports WHERE status = %s AND created_at < %s", ("Resolved", cutoff))
        return cur.rowcount
