-- ==============================================================================
-- SafeBridge AI — PostgreSQL Schema & Security Configuration
-- Compatible with self-hosted PostgreSQL (Docker, Oracle Linux, VM) and Supabase
-- ==============================================================================

-- 1. Students / Accounts Table
-- MOE Privacy Requirement: display_name must store pseudonyms/handles only.
-- Real student identities must never be stored in this database.
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL, -- Pseudonym/handle (e.g. Student-101, BlueFalcon)
    role TEXT NOT NULL DEFAULT 'student',
    active INTEGER NOT NULL DEFAULT 1,
    force_password_change INTEGER NOT NULL DEFAULT 0,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Idempotent column migrations for existing databases
ALTER TABLE students ADD COLUMN IF NOT EXISTS force_password_change INTEGER NOT NULL DEFAULT 0;
ALTER TABLE students ADD COLUMN IF NOT EXISTS failed_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE students ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;

-- 2. Incident Reports Table
CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES students(id) ON DELETE SET NULL,
    anonymous INTEGER NOT NULL DEFAULT 0,
    original_report TEXT NOT NULL,
    incident_summary TEXT,
    category TEXT,
    location TEXT,
    severity TEXT,
    priority TEXT,
    status TEXT NOT NULL DEFAULT 'Pending Review',
    evidence_name TEXT,
    evidence TEXT, -- Base64 encoded file data
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Appointments Table
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    preferred_date TEXT NOT NULL,
    preferred_time TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'Requested',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. Checkins Table (Weekly Wellbeing Signals)
CREATE TABLE IF NOT EXISTS checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    mood INTEGER NOT NULL,
    mood_label TEXT NOT NULL,
    note TEXT,
    week_start TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_student_week UNIQUE (student_id, week_start)
);

-- 5. Counselor Review Notes Table
CREATE TABLE IF NOT EXISTS counselor_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
    counselor_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    note TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Platform Settings Table
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_reports_student ON reports(student_id);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_created ON reports(created_at);
CREATE INDEX IF NOT EXISTS idx_appointments_student ON appointments(student_id);
CREATE INDEX IF NOT EXISTS idx_checkins_student ON checkins(student_id);
CREATE INDEX IF NOT EXISTS idx_counselor_notes_report ON counselor_notes(report_id);

-- 7. Row Level Security (RLS) Configuration (Standard PostgreSQL)
-- Enforces table-level access control on self-hosted PostgreSQL and Supabase
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE counselor_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'students' AND policyname = 'Allow all access to students') THEN
        CREATE POLICY "Allow all access to students" ON students FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'reports' AND policyname = 'Allow all access to reports') THEN
        CREATE POLICY "Allow all access to reports" ON reports FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'appointments' AND policyname = 'Allow all access to appointments') THEN
        CREATE POLICY "Allow all access to appointments" ON appointments FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'checkins' AND policyname = 'Allow all access to checkins') THEN
        CREATE POLICY "Allow all access to checkins" ON checkins FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'counselor_notes' AND policyname = 'Allow all access to counselor_notes') THEN
        CREATE POLICY "Allow all access to counselor_notes" ON counselor_notes FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'settings' AND policyname = 'Allow all access to settings') THEN
        CREATE POLICY "Allow all access to settings" ON settings FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- 8. Platform Default Settings
-- allow_anonymous_reports: '1' -> Anonymous reporting enabled by default (Item 8)
-- external_ai_allowed: '0'     -> Counselor external AI suggestions disabled by default (Item 5)
-- report_retention_days: '30'  -> 30-day retention window for resolved reports (Item 7)
INSERT INTO settings (key, value)
VALUES 
  ('allow_anonymous_reports', '1'),
  ('external_ai_allowed', '0'),
  ('report_retention_days', '30')
ON CONFLICT (key) DO NOTHING;

-- NOTE: All hardcoded demo credentials have been permanently deleted (Item 1).
-- Initial administrator accounts must be provisioned on first launch via secrets.token_urlsafe
-- or created directly by authorized staff through the administrative portal.
